export enum ENV {
  APP_NAME = 'APP_NAME',
  APP_ENV = 'APP_ENV',
  IS_DEV = 'IS_DEV',
  IS_STG = 'IS_STG',
  IS_PRD = 'IS_PRD',
  IS_TEST = 'IS_TEST',
  APP_PORT = 'APP_PORT',

  LOGGER_TYPE = 'LOGGER_TYPE',
  LOGGER_MAX_FILES = 'LOGGER_MAX_FILES',
  LOGGER_LEVEL = 'LOGGER_LEVEL',
  LOGGER_DATABASE_URL = 'LOGGER_DATABASE_URL',

  BODY_SIZE = 'BODY_SIZE',

  SWAGGER_TITLE = 'SWAGGER_TITLE',
  SWAGGER_DESCRIPTION = 'SWAGGER_DESCRIPTION',
  SWAGGER_VERSION = 'SWAGGER_VERSION',
  SWAGGER_FAVICON = 'SWAGGER_FAVICON',
  SWAGGER_ENDPOINT = 'SWAGGER_ENDPOINT',

  CORS_ORIGIN = 'CORS_ORIGIN',
  MAX_IMAGE_BYTES = 'MAX_IMAGE_BYTES',
}

export enum LOGGER_TYPE {
  WINSTON = 'winston',
  CONSOLE = 'console',
}

export enum APP_ENV {
  DEV = 'dev',
  STG = 'stg',
  PRD = 'prd',
  TEST = 'test',
}
